language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - echo 'America/Denver' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script:
  - npm run build
brances:
  only:
  - master
cache:
  - node modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
