language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
brances:
  only:
  - master
cache:
  - node modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
